import { test, expect } from '@playwright/test';
const email=process.env.TEST_EMAIL!,password=process.env.TEST_PASSWORD!;
test('delivery platform guest browsing, search, filters, favorites and persistent cart',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'어떤 음식이 끌리세요?'})).toBeVisible();await expect(page.locator('.delivery-restaurant-card').first()).toBeVisible();
 await page.screenshot({path:'evidence/delivery-desktop.png',fullPage:true});
 await page.getByLabel('음식 또는 가게 검색').fill('치즈버거');await page.getByRole('button',{name:'검색',exact:true}).click();await expect(page.locator('.delivery-restaurant-card')).toHaveCount(3);
 await page.locator('.favorite-button').first().click();await page.getByLabel('가게 필터').selectOption('favorites');await expect(page.locator('.delivery-restaurant-card')).toHaveCount(1);
 await page.locator('.delivery-card-bottom button').first().click();await page.getByRole('button',{name:'장바구니',exact:true}).click();await expect(page.getByRole('heading',{name:'장바구니',exact:true})).toBeVisible();await page.getByRole('button',{name:'수량 늘리기'}).click();await expect(page.getByTestId('cart-quantity')).toHaveText('2');
 await page.reload();await expect(page.locator('.delivery-restaurant-card').first()).toBeVisible();await page.getByRole('button',{name:'장바구니',exact:true}).click();await expect(page.getByTestId('cart-quantity')).toHaveText('2');await page.screenshot({path:'evidence/delivery-cart.png'});
 await page.getByRole('button',{name:'닫기',exact:true}).click();await page.locator('.delivery-card-bottom button').first().click();await expect(page.getByRole('heading',{name:'다른 가게의 메뉴를 담을까요?'})).toBeVisible();await page.getByRole('button',{name:'기존 장바구니 유지하기'}).click();await expect(page.getByTestId('cart-quantity')).toHaveText('2');await page.getByRole('button',{name:'메뉴 삭제'}).click();await expect(page.getByRole('heading',{name:'아직 장바구니가 비어 있어요'})).toBeVisible();
});
test('email login, 10 taste choices, restaurant comparison, checkout and return',async({page})=>{
 await page.goto('/');await expect(page.locator('.delivery-restaurant-card').first()).toBeVisible();await page.getByRole('button',{name:'이메일 로그인',exact:true}).click();await page.getByLabel('이메일',{exact:true}).fill(email);await page.getByLabel('비밀번호',{exact:true}).fill(password);await page.getByRole('dialog').getByRole('button',{name:'로그인',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();
 await page.locator('.taste-entry').click();
 if(await page.getByRole('button',{name:'취향 다시 설정하기'}).isVisible()){await page.getByRole('button',{name:'취향 다시 설정하기'}).click();await page.getByRole('button',{name:'10문항 다시 시작하기'}).click();}
 for(let i=0;i<10;i++){await expect(page.getByRole('heading',{name:'지금 더 먹고 싶은 음식은?'})).toBeVisible();await page.getByTestId(`choice-${i%2}`).click();}
 await page.getByRole('button',{name:'취향 저장하고 추천 보기'}).click();await expect(page.getByRole('heading',{name:'지금, 내 입맛에 가까운 음식'})).toBeVisible();
 await page.locator('.personal-food-card').first().click();await expect(page.locator('.restaurant-item')).toHaveCount(3);await page.getByRole('button',{name:'리뷰 근거 살펴보기'}).first().click();await expect(page.getByText('출처: AI 작성 합성 리뷰',{exact:false})).toBeVisible();await page.getByRole('button',{name:'장바구니 담기'}).first().click();await page.getByRole('button',{name:'장바구니',exact:true}).click();await page.getByRole('button',{name:'수량 늘리기'}).click();await page.getByRole('dialog').getByRole('button',{name:'포장',exact:true}).click();await page.getByRole('button',{name:'테스트 주문하기'}).click();await expect(page.getByRole('heading',{name:'테스트 주문이 접수됐어요!'})).toBeVisible();await page.screenshot({path:'evidence/delivery-checkout.png'});
 await page.getByRole('button',{name:'주문내역 보기'}).click();await expect(page.locator('.history-list article').first()).toContainText('2개 · 포장 · 결제 없음');await page.getByRole('button',{name:'취향에 반영하기'}).click();await expect(page.getByText('새 식사 기록 0개가 기다리고 있어요')).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'지금, 내 입맛에 가까운 음식'})).toBeVisible();await page.getByRole('button',{name:'로그아웃',exact:true}).click();await expect(page.getByRole('button',{name:'이메일 로그인',exact:true})).toBeVisible();
});
test('mobile delivery screen has no horizontal overflow, location and empty search work',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('.delivery-restaurant-card').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'evidence/delivery-mobile.png',fullPage:true});await page.locator('.delivery-location').click();await page.getByLabel('도시 선택').selectOption('busan');await page.getByLabel('장소 선택').selectOption('work');await page.getByRole('button',{name:'이 위치로 설정'}).click();await expect(page.locator('.delivery-location')).toContainText('부산 · 회사');
 await page.getByLabel('음식 또는 가게 검색').fill('없는메뉴테스트');await page.getByRole('button',{name:'검색',exact:true}).click();await expect(page.getByRole('heading',{name:'찾으시는 메뉴가 없어요'})).toBeVisible();await page.getByRole('button',{name:'전체 가게 보기'}).click();await expect(page.locator('.delivery-restaurant-card')).toHaveCount(9);
});
